spring:
  application:
    name: gateway
  boot:
    admin:
      client:
        url: http://localhost:8762
        instance:
          service-base-url: http://localhost:3333
  cloud:
    gateway:
      routes:
        - id: api-1
          uri: lb://WELCOME-SERVICE
          predicates:
            - Path=/welcome
        - id: api-2
          uri: lb://GREAT-SERVICE
          predicates:
            - Path=/great


server:
  port: 3333

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
