spring:
  boot:
    admin:
      client:
        url: http://localhost:8762
        instance:
          service-base-url: http://localhost:9091
application:
  name: great


server:
  port: 9091


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: refresh

msg: GREATMAN
