spring:
  application:
    name: Welcome-Service
  boot:
    admin:
      client:
        url: http://localhost:8762
        instance:
          service-url: http://localhost:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"



