spring:
  boot:
    admin:
      client:
        url: http://localhost:8762
        instance:
          service-url: http://localhost:${server.port}
  application:
    name: welcome

management:
  endpoints:
    web:
      exposure:
        include: "*"

msg: WELCOME MAN



